name: rockchip images
on:
  schedule:
    - cron: '0 9 * * *'

jobs:
    build:
        name: Build OpenWrt Images
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v3
            - name: Build
              run: |
                git clone https://github.com/mj22226/openwrt.git
                cd openwrt
                git config --global user.email you@example.com
                git config --global user.name Your Name
                git remote add openw https://github.com/openwrt/openwrt.git
                git checkout linux-6.1
                git pull --rebase openw master
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                cd feeds/luci
                wget https://gist.githubusercontent.com/mj22226/3888ce030740e7cccbadce571e874913/raw/76e8c2917ddc90499f976f4a0ca2eed01a95efd3/5918.patch
                wget https://gist.githubusercontent.com/mj22226/f6db007367a22a31f9cb1c109a032b45/raw/be368c4f1605f652a001d81548c3a3e14adf6cb7/luci-app-diskman.patch
                git apply 5918.patch
                git apply luci-app-diskman.patch
                cd -
                sed -i "70s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "83s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "193s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "209s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd
                ./scripts/feeds update -a
                ./scripts/feeds install -a -f
                wget https://raw.githubusercontent.com/anon9876543210/rk-build/main/.github/workflows/config.buildinfo -O .config
                make defconfig
                wget https://gist.githubusercontent.com/mj22226/8fe3f95119c0ea42794f8241042b60d5/raw/1e0cb3155a8df2fd36a18629f08c51d3c90ecff9/0001-local-key.patch
                git apply 0001-local-key.patch
                rm 0001-local-key.patch
                make download -j32
                make tools/install -j$(nproc)
                make toolchain/install -j$(nproc)
                make -j$(nproc) 'IGNORE_ERRORS=n m'
                rm -rf bin/targets/rockchip/armv8/packages
            - name: Create release
              uses: ncipollo/release-action@v1.12.0
              with:
                allowUpdates: true
                name: Rockchip v6.1 Images
                tag: 6.1
                replacesArtifacts: true
                prerelease: true
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/rockchip/armv8/*
