name: Build NanoPi R6C/R6S OpenWrt Images
on:
  schedule:
    - cron: '0 14 * * *'
jobs:
    build:
        name: Build NanoPi R6C/R6S OpenWrt Images
        runs-on: ubuntu-latest
        steps:
            - name: Setup Ubuntu
              run: |
                sudo apt update
                sudo apt install -y python3 python3-pip python3-ply python3-distutils python3-pyelftools libpython3-dev swig
            - name: checkout
              uses: actions/checkout@v3
            - name: Build
              run: |
                git clone https://github.com/openwrt/openwrt.git
                cd openwrt
                rm -rf target/linux/rockchip
                rm -f target/linux/generic/config-6.1
                rm -f target/linux/generic/pending-6.1/729-net-phy-realtek-introduce-rtl822x_probe.patch
                rm -rf package/boot/uboot-rockchip
                rm -rf package/boot/arm-trusted-firmware-rockchip
                cd -
                cp -rf rk/* openwrt/
                cd openwrt
                ./scripts/feeds update -a
                ./scripts/feeds install -a
                cd feeds/luci
                wget https://gist.githubusercontent.com/mj22226/3888ce030740e7cccbadce571e874913/raw/76e8c2917ddc90499f976f4a0ca2eed01a95efd3/5918.patch
                wget https://gist.githubusercontent.com/mj22226/f6db007367a22a31f9cb1c109a032b45/raw/be368c4f1605f652a001d81548c3a3e14adf6cb7/luci-app-diskman.patch
                git apply 5918.patch
                git apply luci-app-diskman.patch
                cd -
                sed -i "70s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "83s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "193s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "210s/'0'/'1'/" feeds/luci/applications/luci-app-statistics/root/etc/config/luci_statistics
                sed -i "13s/'1'/'0'/" feeds/packages/utils/dockerd/files/etc/config/dockerd
                ./scripts/feeds update -a
                ./scripts/feeds install -a -f
                mv rkconfig .config
                make defconfig
                make download
                make tools/install -j$(nproc)
                make toolchain/install -j$(nproc)
                make -j$(nproc) 'IGNORE_ERRORS=n m'
                rm -rf bin/targets/rockchip/armv8/packages
                echo "D=$(date +'%Y.%m.%d')" >> $GITHUB_ENV
            - name: Create release
              uses: ncipollo/release-action@v1.12.0
              with:
                allowUpdates: true
                name: OpenWrt NanoPi R6C/R6S ${{ env.D }}
                tag: 6.1
                replacesArtifacts: true
                prerelease: false
                token: "${{ secrets.GITHUB_TOKEN }}"
                artifacts: openwrt/bin/targets/rockchip/armv8/*
